name: deploy to staging
on:
    push:
        branches:
            - "main"
jobs:
   
    redeploy_everything :
        name: "Deploying everything to the staging cluster"
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v2
            - name: "SSH Into server"
              run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
                ssh -i ~/ssh_key pranj@34.0.13.210
                cd bms && git pull
                pnpm install 
                pnpm run build
                pm2 restart fe-server
                pm2 restart http-server
                pm2 restart ws-server


